package net.intelliboard.next.services.database;

public class SQLQueries {

    public static final String VACUUM_QUERY = "vacuum full verbose;";
    public static final String ANALYZE_QUERY = "analyze verbose;";

    public static final String GENERAL_REPORT_QUERY =
            "select schemaname as schema_name,\n" +
                    " relname as table_name,\n" +
                    " n_live_tup as record_number\n" +
                    " from pg_stat_user_tables\n" +
                    " order by schemaname, relname;";


    public static final String FULL_REPORT_QUERY =
            "with db_stats as (\n" +
                    "select pc.relname as table_name,\n" +
                    " c.data_type as type,\n" +
                    " pa.attname as column_name,\n" +
                    " round(ps.null_frac * psu.n_live_tup) as null_values,\n" +
                    " psu.n_live_tup - round(ps.null_frac * psu.n_live_tup) as not_null_values,\n" +
                    " psu.n_live_tup as total\n" +
                    " from pg_class pc\n" +
                    " join pg_namespace pn on pc.relnamespace = pn.oid\n" +
                    " join pg_attribute pa on pa.attrelid = pc.oid\n" +
                    " join information_schema.columns c on c.table_name = pc.relname and c.column_name = pa.attname\n" +
                    " left join pg_stats ps on pc.relname = ps.tablename and pa.attname = ps.attname\n" +
                    " join pg_stat_user_tables psu on pc.oid = psu.relid and pc.relname = psu.relname\n" +
                    " where pc.relkind = 'r'::char\n" +
                    " and c.table_schema = 'public'\n" +
                    " and ps.schemaname = 'public'\n" +
                    " and pn.nspname = 'public'\n" +
                    " and pa.attnum > 0\n" +
                    " order by pc.relname, pa.attnum\n" +
                    " )\n" +
                    " select * from db_stats;";

    public static final String[] ROWS_TEST_ONE_LIST = {
            "activities",
            "activity_completion",
            "activity_types",
            "assignment_activities",
            "assignment_submissions",
            "browsers",
            "categories",
            "courses",
            "enrolment_details",
            "enrolments",
            "forum_activities",
            "forum_discussions",
            "forum_posts",
            "grade_letters",
            "grade_objects",
            "grade_objects_results",
            "login_history",
            "login_stats",
            "lti_activities",
            "operating_systems",
            "org_unit_courses",
            "org_units",
            "quiz_activities",
            "quiz_attempts",
            "quiz_question_answers",
            "quiz_question_relations",
            "quiz_questions",
            "role_assignments",
            "roles",
            "sessions",
            "terms",
            "user_tracking_by_day",
            "user_tracking_total",
            "users"
    };

    public static final String[] ROWS_TEST_THREE_LIST_ONE = {
            "categories",
            "courses",
            "role_assignments",
            "users"
    };

    public static final String[] ROWS_TEST_THREE_LIST_TWO = {
            "incontact_categories",
            "incontact_courses",
            "incontact_role_assignments",
            "incontact_users"
    };

    public static String[][] TEST_QUERY = {
            {"activities", "name"},
            {"activities", "state"},
            {"activities", "created_at"},
            {"activities", "due_at"},
            {"activities", "id"},
            {"activities", "course_id"},
            {"activities", "activity_type_id"},
            {"activities", "activity_object_id"},
            {"activity_completion", "activity_id"},
            {"activity_completion", "user_id"},
            {"activity_completion", "completed_at"},
            {"activity_completion", "id"},
            {"activity_completion", "state"},
            {"activity_types", "name"},
            {"activity_types", "alias"},
            {"activity_types", "id"},
            {"assignment_activities", "name"},
            {"assignment_activities", "start_at"},
            {"assignment_activities", "end_at"},
            {"assignment_activities", "due_at"},
            {"assignment_activities", "created_at"},
            {"assignment_activities", "state"},
            {"assignment_activities", "id"},
            {"assignment_activities", "course_id"},
            {"assignment_activities", "activity_id"},
            {"assignment_submissions", "id"},
            {"assignment_submissions", "assignment_id"},
            {"assignment_submissions", "user_id"},
            {"assignment_submissions", "submitted_at"},
            {"assignment_submissions", "state"},
            {"assignment_submissions", "score"},
            {"assignment_submissions", "feedback"},
            {"browsers", "id"},
            {"browsers", "name"},
            {"categories", "id"},
            {"categories", "name"},
            {"categories", "path"},
            {"categories", "parent_id"},
            {"categories", "is_visible"},
            {"courses", "sis_id"},
            {"courses", "name"},
            {"courses", "code"},
            {"courses", "start_at"},
            {"courses", "end_at"},
            {"courses", "created_at"},
            {"courses", "state"},
            {"courses", "is_visible"},
            {"courses", "id"},
            {"courses", "category_id"},
            {"courses", "term_id"},
            {"courses", "url"},
            {"enrolment_details", "id"},
            {"enrolment_details", "state"},
            {"enrolment_details", "created_at"},
            {"enrolment_details", "updated_at"},
            {"enrolment_details", "enrolment_id"},
            {"enrolment_details", "enrolment_id"},
            {"enrolments", "id"},
            {"enrolments", "user_id"},
            {"enrolments", "course_id"},
            {"enrolments", "role_id"},
            {"enrolments", "last_activity_at"},
            {"enrolments", "visits"},
            {"enrolments", "time_spent"},
            {"enrolments", "completed_activities"},
            {"enrolments", "need_complete_activity"},
            {"enrolments", "is_completed"},
            {"enrolments", "is_completed"},
            {"enrolments", "completed_at"},
            {"forum_activities", "name"},
            {"forum_activities", "created_at"},
            {"forum_activities", "id"},
            {"forum_activities", "sys_id"},
            {"forum_activities", "course_id"},
            {"forum_activities", "activity_id"},
            {"forum_discussions", "name"},
            {"forum_discussions", "description"},
            {"forum_discussions", "last_post_at"},
            {"forum_discussions", "last_post_user_id"},
            {"forum_discussions", "id"},
            {"forum_discussions", "sys_id"},
            {"forum_discussions", "forum_id"},
            {"forum_posts", "id"},
            {"forum_posts", "message"},
            {"forum_posts", "num_replies"},
            {"forum_posts", "state"},
            {"forum_posts", "created_at"},
            {"forum_posts", "sys_discussion_id"},
            {"forum_posts", "user_id"},
            {"forum_posts", "forum_id"},
            {"forum_posts", "discussion_id"},
            {"forum_posts", "parent_post_id"},
            {"grade_letters", "id"},
            {"grade_letters", "grade_letter"},
            {"grade_letters", "min"},
            {"grade_letters", "max"},
            {"grade_objects", "id"},
            {"grade_objects", "title"},
            {"grade_objects", "type"},
            {"grade_objects", "state"},
            {"grade_objects", "max_grade"},
            {"grade_objects", "course_id"},
            {"grade_objects", "activity_id"},
            {"grade_objects_results", "grade_score"},
            {"grade_objects_results", "grade_point"},
            {"grade_objects_results", "comments"},
            {"grade_objects_results", "state"},
            {"grade_objects_results", "graded_at"},
            {"grade_objects_results", "id"},
            {"grade_objects_results", "grade_object_id"},
            {"grade_objects_results", "user_id"},
            {"grade_objects_results", "grade_letter_id"},
            {"login_history", "login_at"},
            {"login_history", "logout_at"},
            {"login_history", "ip"},
            {"login_history", "id"},
            {"login_history", "user_id"},
            {"login_history", "session_id"},
            {"login_history_upd", "id"},
            {"login_history_upd", "user_id"},
            {"login_history_upd", "login_at"},
            {"login_history_upd", "login_at"},
            {"login_history_upd", "logout_at"},
            {"login_history_upd", "ip"},
            {"login_history_upd", "session_id"},
            {"login_stats", "first_login_at"},
            {"login_stats", "last_login_at"},
            {"login_stats", "logins_count"},
            {"login_stats", "user_id"},
            {"lti_activities", "id"},
            {"lti_activities", "created_at"},
            {"lti_activities", "updated_at"},
            {"lti_activities", "tool_name"},
            {"lti_activities", "tool_id"},
            {"lti_activities", "tool_id"},
            {"lti_activities", "launch_url"},
            {"lti_activities", "state"},
            {"lti_activities", "course_id"},
            {"lti_activities", "activity_id"},
            {"lti_activities", "name"},
            {"operating_systems", "id"},
            {"operating_systems", "name"},
            {"org_unit_courses", "id"},
            {"org_unit_courses", "course_id"},
            {"org_unit_courses", "org_unit_id"},
            {"org_units", "id"},
            {"org_units", "name"},
            {"org_units", "type"},
            {"org_units", "created_at"},
            {"org_units", "state"},
            {"org_units", "parent_id"},
            {"quiz_activities", "name"},
            {"quiz_activities", "state"},
            {"quiz_activities", "start_at"},
            {"quiz_activities", "end_at"},
            {"quiz_activities", "due_at"},
            {"quiz_activities", "created_at"},
            {"quiz_activities", "id"},
            {"quiz_activities", "course_id"},
            {"quiz_activities", "activity_id"},
            {"quiz_attempts", "id"},
            {"quiz_attempts", "quiz_id"},
            {"quiz_attempts", "user_id"},
            {"quiz_attempts", "complete_at"},
            {"quiz_attempts", "state"},
            {"quiz_attempts", "score"},
            {"quiz_question_answers", "id"},
            {"quiz_question_answers", "question_id"},
            {"quiz_question_answers", "attempt_id"},
            {"quiz_question_answers", "score"},
            {"quiz_question_relations", "id"},
            {"quiz_question_relations", "quiz_id"},
            {"quiz_question_relations", "question_id"},
            {"quiz_questions", "id"},
            {"quiz_questions", "name"},
            {"quiz_questions", "text"},
            {"quiz_questions", "type"},
            {"quiz_questions", "possible_score"},
            {"role_assignments", "id"},
            {"role_assignments", "context_type"},
            {"role_assignments", "user_id"},
            {"role_assignments", "context_id"},
            {"role_assignments", "role_id"},
            {"roles", "name"},
            {"roles", "alias"},
            {"roles", "type"},
            {"roles", "id"},
            {"roles", "role_id"},
            {"sessions", "ip"},
            {"sessions", "browser"},
            {"sessions", "os"},
            {"sessions", "id"},
            {"terms", "id"},
            {"terms", "name"},
            {"terms", "start_at"},
            {"terms", "end_at"},
            {"terms", "state"},
            {"user_tracking_by_day", "id"},
            {"user_tracking_by_day", "visits"},
            {"user_tracking_by_day", "time_spent"},
            {"user_tracking_by_day", "time_points"},
            {"user_tracking_by_day", "first_access"},
            {"user_tracking_by_day", "last_access"},
            {"user_tracking_by_day", "total_id"},
            {"user_tracking_total", "id"},
            {"user_tracking_total", "context_type"},
            {"user_tracking_total", "first_access"},
            {"user_tracking_total", "last_access"},
            {"user_tracking_total", "visits"},
            {"user_tracking_total", "time_spent"},
            {"user_tracking_total", "ip"},
            {"user_tracking_total", "user_id"},
            {"user_tracking_total", "course_id"},
            {"user_tracking_total", "activity_id"},
            {"user_tracking_total", "browser_id"},
            {"user_tracking_total", "os_id"},
            {"user_tracking_total", "raw_time_spent"},
            {"user_tracking_total", "service_activity_id"},
            {"users", "user_name"},
            {"users", "full_name"},
            {"users", "signup_at"},
            {"users", "email"},
            {"users", "locale"},
            {"users", "country_code"},
            {"users", "last_login_at"},
            {"users", "logins_count"},
            {"users", "sis_id"},
            {"users", "state"},
            {"users", "first_login_at"},
            {"users", "id"}
    };
}
